pipeline {
    agent any
    stages {
        stage('Helm2: install') {
            steps {
                echo "Install Helm 2"
            }
        }
        stage('Trigger Helm Charts'){
            steps{
                script{
                    build job: "../argo/helm1/${BRANCH_NAME}"
                }
            }
        }
    }
}
