pipeline {
    agent any
    stages {
        stage('DBT: build') {
            steps {
                echo "***files list***\n\n"
                sh "ls -ltr"
            }
        }
    }
}
